### ISSUE TITLE
sztpd fails to start

### ISSUE THREAD

**Issue by llabordehpe** [opiproject/sztp#158]
sztpd fails to start with following stack:

sztp-bootstrap-1  | + sztpd sqlite:///:memory:
sztp-bootstrap-1  | Traceback (most recent call last):
sztp-bootstrap-1  |   File "/usr/local/bin/sztpd", line 8, in <module>
sztp-bootstrap-1  |     sys.exit(main())
sztp-bootstrap-1  |   File "/usr/local/lib/python3.10/site-packages/sztpd/__main__.py", line 5, in main
sztp-bootstrap-1  |     def main(argv=None):A=argparse.ArgumentParser(prog='sztpd',formatter_class=argparse.RawDescriptionHelpFormatter,description='SZTPD implements the "bootstrap server" defined in RFC 8572.',epilog='\nExit status code: 0 on success, non-0 on error.  Error output goes to stderr.\n\nThe "cacert" argument is a filepath to a PEM file that contains one or more X.509\nCA certificates used to authenticate the RDBMS\'s TLS certificate.\n\nThe "key" and "cert" arguments are each a filepath to a PEM file that contains\nthe key and certificate that SZTPD should use to authenticate itself to the\nRDBMS.  These parameters must be specified together, and must be specified\nin conjunction with the "cacert" parameter.\n\nThe "database-url" argument has the form "<dialect>:<dialect-specific-path>".\nThree dialects are supported: "sqlite", "postgresql", and "mysql+pymysql".\nThe dialect-specific-path for each of these is described below.\n\nFor the "sqlite" dialect, <dialect-specific-path> follows the format\n"///<sqlite-path>", where <sqlite-path> can be one of:\n\n  :memory:    - an in-memory database (only useful for testing)\n  <filepath>  - an OS-specific filepath to a persisted database file\n\n  Examples:\n\n    $ sztpd sqlite:///:memory:                      (memory)\n    $ sztpd sqlite:///relative/path/to/sztpd.db     (unix)\n    $ sztpd sqlite:////absolute/path/to/sztpd.db    (unix)\n    $ sztpd sqlite:///C:\\path\\to\\sztpd.db           (windows)\n\nFor both the "postgresql" and "mysql+pymysql" dialects, <dialect-specific-path>\nfollows the format "//<user>[:<passwd>]@<host>:<port>/<database-name>".\n\n  Examples:\n\n    The following two examples assume the database is called "sztpd" and\n    that the database server listens on the loopback address with no TLS.\n\n      $ sztpd mysql+pymysql://user:pass@localhost:3306/sztpd\n      $ sztpd postgresql://user:pass@localhost:5432/sztpd\n\n\nPlease see the documentation for more information.\n');A.add_argument('-v','--version',help='show version number and exit.',action='version',version=__version__.__version__);A.add_argument('-C','--cacert',help='path to certificates used to authenticate the database (see below for details).');A.add_argument('-c','--cert',help='path to cert used to authenticate SZTPD to the database (see below for details).');A.add_argument('-k','--key',help='path to key used to authenticate SZTPD to the database (see below for details).');A.add_argument('database_url',help='see below for details.',metavar='database-url');B=A.parse_args();return sztpd.run(B.database_url,B.cacert,B.cert,B.key)
sztp-bootstrap-1  |   File "/usr/local/lib/python3.10/site-packages/sztpd/sztpd.py", line 54, in run
sztp-bootstrap-1  |     except Exception as H:raise H;return 1
sztp-bootstrap-1  |   File "/usr/local/lib/python3.10/site-packages/sztpd/sztpd.py", line 53, in run
sztp-bootstrap-1  |     try:A=DataAccessLayer(O,J,K,L,json.loads(getattr(yl,'nbi_'+B)()),'wn-sztpd-'+B,B)
sztp-bootstrap-1  |   File "/usr/local/lib/python3.10/site-packages/sztpd/yangcore/dal.py", line 79, in __init__
sztp-bootstrap-1  |     else:A.app_ns=app_ns;A._create(B,C,D,E,F,opaque)
sztp-bootstrap-1  |   File "/usr/local/lib/python3.10/site-packages/sztpd/yangcore/dal.py", line 660, in _create
sztp-bootstrap-1  |     A.metadata=sa.MetaData(bind=A.engine,schema=A.db_schema);C=sa.Table(_G,A.metadata,sa.Column(_M,sa.Integer,primary_key=_E),sa.Column(_I,sa.Integer,unique=_E),sa.Column(F,sa.String(250),unique=_E),sa.Column(_O,jsob_type));A.metadata.create_all()
sztp-bootstrap-1  | TypeError: **MetaData.__init__() got an unexpected keyword argument 'bind'**
sztp-bootstrap-1 exited with code 1

**MetaData bind argument is deprecated and will be removed from sqlalchemy2.0.0**: https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_46/lib/sqlalchemy/sql/schema.py#L4413-L4418

**Comment by glimchb** [comment]
thanks for filing this issue

**Comment by glimchb** [comment]
I see that new PRs like #157 and #156 started to fail and I didn't have a chance to investigate why
so thanks for finding this issue and fixing it
I wonder now why CI didn't catch it earlier and only now started to fail...

**Comment by llabordehpe** [comment]
> 

sqlachemy v2.0.0 was relesed just a few days ago: https://pypi.org/project/SQLAlchemy/#history
