### ISSUE TITLE
Update outdated Readme

### ISSUE THREAD

**Issue by E5DR** [opiproject/sztp#229]
It appears that parts of the readme are outdated and showcase commands that do not work anymore.

To be specific, various sections show examples using the `simulator` container, which does not exist anymore and was removed with [Pull request #175](https://github.com/opiproject/sztp/pull/175) a few months ago (apparently the simulator is not needed anymore since the go implementation exists now).
The usage examples for the simulator should be removed or updated to show how the go implementation is to be used.

**Comment by glimchb** [comment]
https://github.com/search?q=repo%3Aopiproject%2Fsztp+simulator+language%3AMarkdown&type=code&l=Markdown

**Comment by glimchb** [comment]
Will copy correct commands from https://github.com/opiproject/sztp/blob/main/scripts/tests.sh
