### ISSUE TITLE
add binaries to package release (goreleaser)

### ISSUE THREAD

**Issue by glimchb** [opiproject/sztp#432]
today we only publish docker
in real life this is too early in the system to have docker running
consider publishing binaries as well
see if we can leverage https://github.com/marketplace/actions/goreleaser-action

read https://medium.com/trendyol-tech/the-fanciest-way-of-releasing-go-binaries-with-goreleaser-dbbd3d44c7fb

**Comment by h0lyalg0rithm** [comment]
@glimchb I am gonna work on this issue, Do we build binaries for linux only?

**Comment by glimchb** [comment]
> @glimchb I am gonna work on this issue, Do we build binaries for linux only?

yes, Linux only, but both x86 and arm64 arch
