### ISSUE TITLE
better OS version parsing

### ISSUE THREAD

**Issue by glimchb** [opiproject/sztp#433]
see https://github.com/opiproject/sztp/blob/fd911e237591dfac773f98b20e40758aa2e1907b/sztp-agent/pkg/secureagent/utils.go#L63-L64

maybe better use:
```
import "github.com/go-ini/ini"
cfg, err := ini.Load("/etc/os-release")
cfg.Section("").Key("VERSION").String()
```

or existing go constants... like `runtime.GOOS`...

**Comment by glimchb** [comment]
@Xeckt wanna take this ?

**Comment by Xeckt** [comment]
I can take this on. Will have to tackle it somewhat later as we're finishing a project at work.

**Comment by Xeckt** [comment]
@glimchb - How would you like this done? Because if we want to fetch OS, do we want to create a separate util function for it in the event it needs to be handle elsewhere in the future? That way we can make the logic a little longer so it's more reliable to parse.

**Comment by Xeckt** [comment]
I don't know how important the `name` of the OS being specific to a distribution is. A simple, reliable solution could be to syscall `uname`. Something like this (just a working example I came up with):

```go
func GetOs() {
	var u syscall.Utsname
	if err := syscall.Uname(&u); err != nil {
		log.Fatal(err)
	}
	fmt.Println(
		utsToString(u.Machine),
		utsToString(u.Release),
	)
}

func utsToString(uname [65]int8) string {
	var b [65]byte
	for i := 0; uname[i] != 0; i++ {
		b[i] = uint8(uname[i])
	}
	return string(b[:])
}
```

**Comment by glimchb** [comment]
For now i think we should go with simple improvement 
```
import "github.com/go-ini/ini"
cfg, err := ini.Load("/etc/os-release")
cfg.Section("").Key("VERSION").String()
```

**Comment by Xeckt** [comment]
That's fine but we can do it with built in packages over adding more dependencies?

**Comment by glimchb** [comment]
> replaceQuotes(strings.Split(linesInFileContains(OS_RELEASE_FILE, "NAME"), "=")[1])

this looks ugly

> 	if err := syscall.Uname(&u); err != nil {
I don't ike syscalls here, espcially if we run inside docker, we can easily map os-release file inside container

> Plus VERSION keys don't always exist on os-release files
understood, we can deal with this when requirement will come up

**Comment by Xeckt** [comment]
Mapping os-release seems to add another layer of logic that doesn't seem needed? Though I like the idea of mapping inside a container, which begs the questions:

1. Does this mean that the user will have to map the file themselves? If you are adamant about using os-release?
2. Is it necessary to have os information inside the container about the host, if it's running in a container? Isn't it better applicable to have os information about the isolated environment it will actually run in?
3. Can we not just use syscalls for the host and then manually move the pulled out information to the container if it's an absolute requirement to have host info? If not, then how about reading the `os-release` file and carrying the info over into the container without mapping it?

Syscalls just seem the more reliable way in my eyes. I understand `/etc/os-release` is present on all linux machines, and if you want to fetch the real distribution name instead, then it does make sense. There are prettier ways to do it than the current without dependencies. But as far as I'm concerned, knowing the os, the architecture, and kernel version is enough for whatever you may use it for.
