### ISSUE TITLE
 move downloadAndValidateImage(), copyConfigurationFile(), launchScriptsConfiguration() to a new file

### ISSUE THREAD

**Issue by glimchb** [opiproject/sztp#446]
@h0lyalg0rithm if you wanna work on this

**Comment by h0lyalg0rithm** [comment]
@glimchb Please assign it to me

**Comment by h0lyalg0rithm** [comment]
@glimchb Do you have suggestion for a file name

**Comment by glimchb** [comment]
> @glimchb Do you have suggestion for a file name

nope, whatever you feel is best
